
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'project_example'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'profile_example'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Define variables here
vars:
  dw_database: dw
  dw_schema: public
  raw_database: raw

# Define seeds here
seeds:
  project_example:
    schema: source_internal

# Define snapshots
snapshots:
  project_example:
    +target_schema: public
    +target_database: raw
    +source_schema: public
    +source_database: raw
    
# Define models
models:
  project_example: 
    1_source:
      source_example:
        +enabled: true # the model is enabled and will run with dbt
        +transient: false # transient or permanent
        +materialized: table # table or view
        +schema: source_example # database schema to use, could use variable here
        +database: raw # database to use, could use variable here 

