{{ config(
    post_hook="create or replace table {{ var('dw_database') }}.{{ var('dw_schema') }}.dim_date clone {{ this }};",
    tags=["dimension","dim_date"]
) }}

WITH source_data AS (

    SELECT 
        date,
        cast(datename as varchar(50)) as datename,
        year,
        cast(yearname as varchar(50)) as yearname,
        month,
        cast(monthname as varchar(50)) as monthname,
        week,
        cast(weekname as varchar(50)) as weekname,
        dayofyear,
        cast(dayofyearname as varchar(50)) as dayofyearname,
        dayofmonth,
        cast(dayofmonthname as varchar(50)) as dayofmonthname,
        dayofweek,
        cast(dayofweekname as varchar(50)) as dayofweekname,
        weekofyear,
        cast(weekofyearname as varchar(50)) as weekofyearname,
        monthofyear,
        cast(monthofyearname as varchar(50)) as monthofyearname,
        currentday,
        yesterday,
        currentweek,
        previousweek,
        last7days,
        previous30days,
        monthtodate,
        currentmonth,
        currentmonthlag,
        previousmonth,
        previousmonthmonthtodate,
        monthovermonth,
        last3months,
        yeartodate,
        yeartodatemonthovermonth,
        monthtodateyearoveryear,
        yeartodateyearoveryear,
        last6months,
        currentyear,
        previousyear,
        last12months,
        yeartodateyearoveryearpm,
        yeartodatepm,
        businessdaycount,
        dealerbusinessdaycount,
        businessdayofmonth,
        businessdaysinmonth,
        businessdaysremaining,
        cast(spiff_period as varchar(50)) as spiff_period,
        cast(spiff_currentperiod as varchar(50)) as spiff_currentperiod,
        cast(spiff_periodrange as varchar(50)) as spiff_periodrange,
        cast(monthofyeartext as varchar(50)) as monthofyeartext,
        spiff_period_key
    FROM {{ ref('stg_dim_date') }}

    union all 

    select 
        NULL as date,
        'Unknown' as datename,
        NULL as year,
        NULL as yearname,
        NULL as month,
        NULL as monthname,
        NULL as week,
        NULL as weekname,
        NULL as dayofyear,
        NULL as dayofyearname,
        NULL as dayofmonth,
        NULL as dayofmonthname,
        NULL as dayofweek,
        NULL as dayofweekname,
        NULL as weekofyear,
        NULL as weekofyearname,
        NULL as monthofyear,
        NULL as monthofyearname,
        0 as currentday,
        NULL as yesterday,
        0 as currentweek,
        NULL as previousweek,
        NULL as last7days,
        NULL as previous30days,
        NULL as monthtodate,
        0 as currentmonth,
        0 as currentmonthlag,
        NULL as previousmonth,
        NULL as previousmonthmonthtodate,
        NULL as monthovermonth,
        NULL as last3months,
        NULL as yeartodate,
        NULL as yeartodatemonthovermonth,
        NULL as monthtodateyearoveryear,
        NULL as yeartodateyearoveryear,
        NULL as last6months,
        0 as currentyear,
        NULL as previousyear,
        NULL as last12months,
        NULL as yeartodateyearoveryearpm,
        NULL as yeartodatepm,
        NULL as businessdaycount,
        NULL as dealerbusinessdaycount,
        NULL as businessdayofmonth,
        NULL as businessdaysinmonth,
        NULL as businessdaysremaining,
        NULL as spiff_period,
        NULL as spiff_currentperiod,
        NULL as spiff_periodrange,
        NULL as monthofyeartext,
        0 as spiff_period_key

    )

SELECT
    {{ dbt_utils.surrogate_key(['date']) }} AS date_key, 
    *
FROM
    source_data
ORDER BY
    DATE ASC